## Cross-validation procedure

Let $\mathbb{K}$ denote the set of kernel functions and $\mathcal{B}(K)$ the set of bandwidth selection 
procedures available for kernel $K$. In addition, let $\mathbb{P}$ denote the set of post-processing configurations. 
Each $P \in \mathbb{P}$ specifies a rule for computing a local mean of the density curves and is defined by a 
mean-computation mode and an associated window length $w$. In the empirical application, the mean-computation mode 
may correspond to an expanding or rolling scheme, while the window length determines the number of past curves 
used in the computation. The set $\mathbb{P}$ also includes the configuration corresponding to no
post-processing, for which the transformation operator reduces to the
identity mapping $\mathcal{T}_{P}(f_t)=f_t$.


The complete *tuning* space is defined as
\begin{equation}
\Pi= \{(K, B, \eta, P) : K \in \mathbb{K},\; B \in \mathcal{B}(K),\; P \in \mathbb{P}\},
\end{equation}
where $\eta$ captures auxiliary parameters, such as the degrees of freedom for the Student-t kernel or the robust scale estimator 
for Silverman’s rule. In the present setting, these correspond to the degrees of freedom parameter for the 
Student-$t$ kernel or the use of a robust standard deviation estimator in 
the Silverman bandwidth rule.
Each configuration $\theta_j \in \Theta$ is therefore defined as
\begin{equation}
\pi_j = (K_j, B_j, \eta_j, P_j), \quad j = 1,\dots,M.
\end{equation}

Let $r_{t1},\dots,r_{tn_t}$ denote the intraday log-returns observed on day $t$, 
for $t=1,\dots,T$. For a given configuration $(K_j,B_j,\eta_j)$, the raw daily density estimates are first obtained using the kernel density estimator


\begin{equation}
f_t^{(K_j,B_j,\eta_j)}(x)
=
\frac{1}{n_t h_t^{(j)}}
\sum_{i=1}^{n_t}
K_j\!\left(\frac{r_{ti}-x}{h_t^{(j)}};\eta_j\right),
\end{equation}

where $h_t^{(j)}$ is the bandwidth determined by the rule $B_j$.
This produces the functional time series of densities
\begin{equation}
\mathcal{X}^{(K_j,B_j,\eta_j)}=\{f_1^{(K_j,B_j,\eta_j)},\dots,f_T^{(K_j,B_j,\eta_j)}\}.
\end{equation}

The post-processing configuration $P_j$ is then applied through a transformation operator $\mathcal{T}_{P_j}$ acting on the sequence of density curves. This yields the transformed functional time series
\begin{align*}
\mathcal{Z}^{(\theta_j)} &= \{Z_1^{(\theta_j)},\dots,Z_T^{(\theta_j)}\}, \\
Z_t^{(\theta_j)}         &= \big(\mathcal{T}_{P_j}(\mathcal{X}^{(K_j,B_j,\eta_j)})\big)_t.
\end{align*}

The sample is partitioned into three segments: an initial estimation period,
a validation period, and a test period. Let $t_0$ denote the size of the
initial estimation window and let $t_v$ denote the final index of the
validation period, where $t_0 < t_v < T$. The observations
$t=1,\dots,t_0$ form the initial estimation sample. Forecasts corresponding
to $t=t_0+1,\dots,t_v$ constitute the validation period used for model
selection, while forecasts for $t=t_v+1,\dots,T$ form the test period used
for final forecast evaluation.
For each configuration $\theta_i$, forecasts are generated using an
expanding window scheme. At each step $t=t_0,\dots,T-1$, the forecasting
model is estimated using the sample
${Z_1^{(\theta_i)},\dots,Z_t^{(\theta_i)}}$ and produces a one-step-ahead
forecast $\widehat{Z}_{t+1}^{(\theta_i)}$. This procedure yields the sequence
$
\widehat{Z}_{t_0+1}^{(\theta_i)},\widehat{Z}_{t_0+2}^{(\theta_i)},\dots,
\widehat{Z}_{T}^{(\theta_i)}.
$
In the empirical application considered in this dissertation, the initial
estimation window is set to $t_0=100$, and the validation period ends at
$t_v=180$. Consequently, the validation and test partitions contain
80 and 67 evaluation curves, respectively.

\begin{equation}
L_{ij}
=
\frac{1}{t_v - t_0}
\sum_{t=t_0}^{t_v-1}
D\!\left(
Z_{t+1}^{(\theta_j)},
\widehat{Z}_{t+1}^{(\theta_i)}
\right).
\end{equation}

which yields an $M \times M$ loss matrix. Finally, the selected configuration is


\begin{equation*}
\theta^*
=
\arg\min_{\theta_i \in \Theta}
\frac{1}{M}
\sum_{j=1}^{M}
L_{ij}.
\end{equation*}

* Kernel options:
    - gaussian
    - epanechnikov
    - student-t
* Bandwidth selection method:
    - ROT
    - CV
    - Adaptive
* Postprocessing configurations:
    - No postprocessing (False)
    - 5 days (w5)
    - 21 days (w21)
    - 63 days (w63)

In out configuration, M = 53.

In [1]:
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import joblib

In [4]:
df_cv = joblib.load('../data/processed/cv_divergences_long_20260316.jbl')
df_cv["forecast_kde_pp_params"] = df_cv["forecast_kde_params"] + "___" + df_cv["forecast_pp_params"]
display(df_cv.head())
df_cv.shape

,kde_model,forecast_model,forecast_kde_params,forecast_pp_params,forecast_dFPC_dimension,forecast_VAR_q,date,KLD,JSD,L1_norm,L2_norm,LINF_norm,forecast_kde_pp_params
0,gaussian_rot_robust___False,gaussian_adaptive___rolling_w21___4___1,gaussian_adaptive,rolling_w21,4,1,2025-05-05,4.463318,0.259433,132390.399380,9300.290670,1423.011034,gaussian_adaptive___rolling_w21
1,gaussian_rot_robust___False,gaussian_adaptive___rolling_w21___4___1,gaussian_adaptive,rolling_w21,4,1,2025-05-06,4.747499,0.286736,136876.520476,9607.463644,1460.064834,gaussian_adaptive___rolling_w21
2,gaussian_rot_robust___False,gaussian_adaptive___rolling_w21___4___1,gaussian_adaptive,rolling_w21,4,1,2025-05-07,4.524809,0.260094,128365.689601,8981.680620,1361.856441,gaussian_adaptive___rolling_w21
3,gaussian_rot_robust___False,gaussian_adaptive___rolling_w21___4___1,gaussian_adaptive,rolling_w21,4,1,2025-05-08,6.517256,0.328244,153828.869188,10192.001729,1560.988364,gaussian_adaptive___rolling_w21
4,gaussian_rot_robust___False,gaussian_adaptive___rolling_w21___4___1,gaussian_adaptive,rolling_w21,4,1,2025-05-09,3.072839,0.173923,101820.998518,7167.118634,1072.201651,gaussian_adaptive___rolling_w21

(5580900, 13)

* kde_model: the database $\theta_j$
* forecast_kde_pp_params: kernel, bandwidth and postprocessing params for forecasting with $\theta_i$
* KLD, JSD, L-norms = $D(\theta_{tj}, \theta_{ti})$

In [5]:
# Top models by kernel + bandwidth selection method
df_cv.groupby("forecast_kde_params")["KLD"].mean().sort_values()

forecast_kde_params
epanechnikov_adaptive                1.279110
gaussian_adaptive                    1.434770
epanechnikov_rot_robust              1.492843
epanechnikov_rot                     1.619572
t-student_cross_validate_df=5_loo    1.683783
t-student_cross_validate_df=4_loo    1.689085
t-student_cross_validate_df=3_loo    1.705115
gaussian_cross_validate_loo          1.748596
t-student_adaptive_df=5              1.764021
t-student_adaptive_df=4              1.764443
t-student_adaptive_df=3              1.767298
gaussian_rot                         1.804581
gaussian_rot_robust                  1.959726
Name: KLD, dtype: float64

In [6]:
# Top models by postprocessing method
df_cv.groupby("forecast_pp_params")["KLD"].mean().sort_values()

forecast_pp_params
rolling_w5     0.954687
expanding      1.229258
rolling_w21    1.476562
False          2.484157
rolling_w63    2.751588
Name: KLD, dtype: float64

In [ ]:
criterion = "forecast_pp_params"

results_by_criterion = df_cv.loc[:, [criterion, 'KLD', 'JSD', 'L1_norm', 'L2_norm', 'LINF_norm']]
rbc_long = results_by_criterion.melt(id_vars=[criterion], var_name="metric")
rbc_long[criterion] = rbc_long.loc[:,criterion].apply(str)

if rbc_long[criterion].nunique() >= len(['KLD', 'JSD', 'L1_norm', 'L2_norm', 'LINF_norm']):
    columns_by = None
    rows_by   = "metric"
    aspect=3
else:
    columns_by = "metric"
    rows_by   =  None
    aspect=1

plt.figure(figsize=(10, 5))

print(criterion)
g = sns.catplot(
    data=rbc_long,
    x=criterion,
    y="value",
    row=rows_by,
    col=columns_by,
    kind="box",
    hue=criterion,
    sharey=False,
    sharex=False,
    height=3,
    aspect=aspect,
    saturation=.5,
    showfliers=False,
)

plt.suptitle(f"Results by {criterion}",y=1.03)

plt.show()

In [8]:
# Top models by kernel + bandwidth selection + postprocessing method
df_cv.groupby("forecast_kde_pp_params")["KLD"].mean().sort_values()

forecast_kde_pp_params
t-student_adaptive_df=3___rolling_w5               0.807961
t-student_cross_validate_df=3_loo___rolling_w5     0.815676
t-student_adaptive_df=4___rolling_w5               0.822652
t-student_cross_validate_df=4_loo___rolling_w5     0.824431
t-student_cross_validate_df=5_loo___rolling_w5     0.829342
t-student_adaptive_df=5___rolling_w5               0.833066
epanechnikov_rot_robust___rolling_w5               0.873882
gaussian_adaptive___rolling_w5                     0.884932
epanechnikov_rot___rolling_w5                      0.885023
epanechnikov_adaptive___expanding                  0.894040
gaussian_adaptive___expanding                      0.949534
epanechnikov_adaptive___rolling_w5                 0.950560
gaussian_cross_validate_loo___rolling_w5           1.022110
t-student_adaptive_df=5___expanding                1.029869
t-student_adaptive_df=4___expanding                1.054301
t-student_adaptive_df=3___expanding                1.092941
t-student_cross_validate_df=3_loo___expanding      1.202743
t-student_cross_validate_df=4_loo___expanding      1.244295
t-student_cross_validate_df=5_loo___expanding      1.270552
t-student_cross_validate_df=5_loo___rolling_w21    1.276975
gaussian_rot___rolling_w5                          1.277398
t-student_cross_validate_df=4_loo___rolling_w21    1.302964
epanechnikov_rot_robust___expanding                1.333550
t-student_cross_validate_df=3_loo___rolling_w21    1.347784
epanechnikov_rot___expanding                       1.454272
gaussian_rot___expanding                           1.481680
gaussian_cross_validate_loo___expanding            1.484345
t-student_adaptive_df=3___rolling_w21              1.490218
gaussian_rot_robust___expanding                    1.517793
t-student_adaptive_df=4___rolling_w21              1.539272
gaussian_cross_validate_loo___rolling_w21          1.552282
t-student_adaptive_df=5___rolling_w21              1.573295
gaussian_rot_robust___rolling_w5                   1.612546
gaussian_adaptive___rolling_w21                    1.730955
epanechnikov_adaptive___False                      1.992731
gaussian_adaptive___False                          2.173658
epanechnikov_rot_robust___False                    2.271096
t-student_adaptive_df=5___False                    2.365093
t-student_adaptive_df=4___False                    2.436068
t-student_cross_validate_df=5_loo___rolling_w63    2.462364
epanechnikov_rot___False                           2.519420
t-student_cross_validate_df=3_loo___False          2.519744
t-student_cross_validate_df=4_loo___rolling_w63    2.521343
t-student_adaptive_df=3___False                    2.547883
t-student_cross_validate_df=4_loo___False          2.552394
t-student_cross_validate_df=5_loo___False          2.579681
t-student_cross_validate_df=3_loo___rolling_w63    2.639628
gaussian_rot___False                               2.656016
gaussian_rot_robust___False                        2.786654
t-student_adaptive_df=3___rolling_w63              2.897485
gaussian_cross_validate_loo___False                2.927924
t-student_adaptive_df=4___rolling_w63              2.969922
t-student_adaptive_df=5___rolling_w63              3.018784
Name: KLD, dtype: float64

In [9]:
# Top models by kernel + bandwidth selection + postprocessing + dimensions + VAR(q) method
df_cv.groupby("forecast_model")["KLD"].mean().sort_values()

forecast_model
t-student_adaptive_df=3___rolling_w5___4___4    0.805081
t-student_adaptive_df=3___rolling_w5___5___4    0.805283
t-student_adaptive_df=3___rolling_w5___3___4    0.805368
t-student_adaptive_df=3___rolling_w5___2___4    0.805899
t-student_adaptive_df=3___rolling_w5___3___2    0.805987
                                                  ...
gaussian_rot_robust___False___6___3             3.132552
gaussian_rot_robust___False___5___2             3.145348
gaussian_rot_robust___False___6___4             3.391092
gaussian_rot_robust___False___5___4             3.471076
gaussian_rot_robust___False___6___2             3.591010
Name: KLD, Length: 1060, dtype: float64

In [15]:
df_test = df_cv.groupby("forecast_model")["KLD"].mean().sort_values().reset_index()
df_test[df_test.forecast_model.str.contains("___2___1")]

                                         forecast_model       KLD
13         t-student_adaptive_df=3___rolling_w5___2___1  0.808741
28    t-student_cross_validate_df=3_loo___rolling_w5...  0.815480
57         t-student_adaptive_df=4___rolling_w5___2___1  0.821658
60    t-student_cross_validate_df=4_loo___rolling_w5...  0.823288
83    t-student_cross_validate_df=5_loo___rolling_w5...  0.828409
105        t-student_adaptive_df=5___rolling_w5___2___1  0.831321
133        epanechnikov_rot_robust___rolling_w5___2___1  0.874395
143              gaussian_adaptive___rolling_w5___2___1  0.877672
166               epanechnikov_rot___rolling_w5___2___1  0.885808
198    gaussian_cross_validate_loo___rolling_w5___2___1  0.893396
206           epanechnikov_adaptive___expanding___2___1  0.897247
239          epanechnikov_adaptive___rolling_w5___2___1  0.951137
253               gaussian_adaptive___expanding___2___1  0.961801
254                   gaussian_rot___rolling_w5___2___1  0.964528
259            gaussian_rot_robust___rolling_w5___2___1  1.003926
279         t-student_adaptive_df=5___expanding___2___1  1.039184
302         t-student_adaptive_df=4___expanding___2___1  1.063704
323         t-student_adaptive_df=3___expanding___2___1  1.100498
333             gaussian_rot_robust___expanding___2___1  1.144518
335   gaussian_cross_validate_loo___rolling_w21___2___1  1.156253
356   t-student_cross_validate_df=3_loo___expanding_...  1.218500
385   t-student_cross_validate_df=5_loo___rolling_w2...  1.261135
386   t-student_cross_validate_df=4_loo___expanding_...  1.261861
408                    gaussian_rot___expanding___2___1  1.270886
423   t-student_cross_validate_df=4_loo___rolling_w2...  1.288529
430   t-student_cross_validate_df=5_loo___expanding_...  1.291070
465   t-student_cross_validate_df=3_loo___rolling_w2...  1.335269
501         epanechnikov_rot_robust___expanding___2___1  1.383285
525     gaussian_cross_validate_loo___expanding___2___1  1.455067
547                epanechnikov_rot___expanding___2___1  1.476535
548       t-student_adaptive_df=3___rolling_w21___2___1  1.478801
578       t-student_adaptive_df=4___rolling_w21___2___1  1.527478
599       t-student_adaptive_df=5___rolling_w21___2___1  1.559897
635             gaussian_adaptive___rolling_w21___2___1  1.693129
674               epanechnikov_adaptive___False___2___1  1.981527
712                   gaussian_adaptive___False___2___1  2.192375
724             epanechnikov_rot_robust___False___2___1  2.264888
737                 gaussian_rot_robust___False___2___1  2.312186
745             t-student_adaptive_df=5___False___2___1  2.354483
769             t-student_adaptive_df=4___False___2___1  2.422796
785   t-student_cross_validate_df=5_loo___rolling_w6...  2.454318
828                    epanechnikov_rot___False___2___1  2.513712
829   t-student_cross_validate_df=3_loo___False___2___1  2.514789
830   t-student_cross_validate_df=4_loo___rolling_w6...  2.515101
843                        gaussian_rot___False___2___1  2.519033
876             t-student_adaptive_df=3___False___2___1  2.537790
887   t-student_cross_validate_df=4_loo___False___2___1  2.546085
917   t-student_cross_validate_df=5_loo___False___2___1  2.571042
940   t-student_cross_validate_df=3_loo___rolling_w6...  2.628515
985       t-student_adaptive_df=3___rolling_w63___2___1  2.897397
1004        gaussian_cross_validate_loo___False___2___1  2.937091
1019      t-student_adaptive_df=4___rolling_w63___2___1  2.967802
1040      t-student_adaptive_df=5___rolling_w63___2___1  3.017319

## Summary

Best model according to CV: t-student_adaptive_df=3___rolling_w5___4___4  <br>
Best post-processing method: rolling 5 weeks <br>
Best kernel + bandwidth: epanechnikov_adaptive <br>