In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import ParameterGrid

import sys
sys.path.append("..")
from src.preprocessing import df_to_densities
from src.forecasting import cv


import warnings
from scipy.integrate import IntegrationWarning

warnings.filterwarnings("ignore", category=RuntimeWarning)
warnings.filterwarnings("ignore", category=IntegrationWarning)

Steps: <br>
1. Use cross-validation to select the best parameters for in-sample KDE <br>
2. Use cross-validation to select the number of dimensions for the dFPC using the resulting parameters for KDE in 1.

In [2]:
# Data
data_path = "../data/processed/"
returns_path = ''.join([data_path, 'ibovespa_treated.xlsx'])
df = pd.read_excel(returns_path, index_col="time")

# 1. Selecting KDE parameters

In [3]:
# Parameters to cross-validate
density_param_grid_0 = [
    {'kernel': ['gaussian', 'epanechnikov'],
        'bandwidth': ['silverman', 'scott'],#, 'cv'],
        'adaptive': [True, False]}, 
    {'kernel': ['t_student'], 
        'df': range(2,6),
        'bandwidth': ['silverman', 'scott'],#, 'cv'],
        'adaptive': [True, False]}]

density_param_grid = list(ParameterGrid(density_param_grid_0))
len(density_param_grid)

24

In [4]:
params_dict = {}
records = []

normalize_options = [True, False]
total_params = len(density_param_grid) * len(normalize_options)
i=1
KdFPC_kwargs = {
    "lag_max": 5,
    "alpha": 0.10,
    "du": 0.05,
    "B": 1000,
    "p": 5,
    # "u": df_lqds_support,
    "select_ncomp": False,
    # "dimension": 2
}
for normalize in normalize_options:
    for d in range(2,7):
        KdFPC_kwargs.update(
            {"dimension": d}
            )
        for params in density_param_grid:
            print(f"({i}/{total_params}) | Normalize = {normalize} | {params}")
            i += 1

            df_support, df_densities = df_to_densities(
                                            df, 
                                            params, 
                                            normalize_densities=normalize,
                                            verbose=False)
            try:
                cv_measures = cv(df_densities, df_support, initial_window=100)
            except Exception as e:
                print(f"\t ERROR: {e}")
                continue
            for m in cv_measures:
                record = {
                    # density
                    "normalized_density": normalize,
                    
                    # parameters
                    "kernel": params["kernel"],
                    "bandwidth": params["bandwidth"],
                    "adaptive": params["adaptive"],

                    # CV info
                    "fold": m["fold"]+1,
                    "method": m["method"],

                    # metrics
                    "dFPC_dimensions":   d,
                    "KLD": float(m["KLD"]),
                    "JSD": float(m["JSD"]),
                    "L_1": float(m["L_1"]),
                    "L_2": float(m["L_2"]),
                    "L_INFTY": float(m["L_INFTY"]),
                }

                records.append(record)
            
results_df = pd.DataFrame(records)

(1/48) | Normalize = True | {'adaptive': True, 'bandwidth': 'silverman', 'kernel': 'gaussian'}
	>>> cv 1/149
	 ERROR: Array must not contain infs or NaNs
(2/48) | Normalize = True | {'adaptive': True, 'bandwidth': 'silverman', 'kernel': 'epanechnikov'}
	>>> cv 1/149
	 ERROR: Array must not contain infs or NaNs
(3/48) | Normalize = True | {'adaptive': True, 'bandwidth': 'scott', 'kernel': 'gaussian'}
	>>> cv 1/149
	>>> cv 2/149
	>>> cv 3/149
	>>> cv 4/149
	>>> cv 5/149
	>>> cv 6/149
	>>> cv 7/149
	>>> cv 8/149
	>>> cv 9/149
	>>> cv 10/149
	>>> cv 11/149
	>>> cv 12/149
	>>> cv 13/149
	>>> cv 14/149
	>>> cv 15/149
	>>> cv 16/149
	>>> cv 17/149
	>>> cv 18/149
	>>> cv 19/149
	>>> cv 20/149
	>>> cv 21/149
	>>> cv 22/149
	>>> cv 23/149
	>>> cv 24/149
	>>> cv 25/149
	>>> cv 26/149
	>>> cv 27/149
	>>> cv 28/149
	>>> cv 29/149
	>>> cv 30/149
	>>> cv 31/149
	>>> cv 32/149
	>>> cv 33/149
	>>> cv 34/149
	>>> cv 35/149
	>>> cv 36/149
	>>> cv 37/149
	>>> cv 38/149
	>>> cv 39/149
	>>> cv 40/149
	>>> cv 41/149
	>>> cv 42/149
	>>> cv 43/149
	>>> cv 44/149
	>>> cv 45/149
	>>> cv 46/149
	>>> cv 47/149
	>>> cv 48/149
	>>> cv 49/149
	>>> cv 50/149
	>>> cv 51/149
	>>> cv 52/149
	>>> cv 53/149
	>>> cv 54/149
	>>> cv 55/149
	>>> cv 56/149
	>>> cv 57/149
	>>> cv 58/149
	>>> cv 59/149
	>>> cv 60/149
	>>> cv 61/149
	>>> cv 62/149
	>>> cv 63/149
	>>> cv 64/149
	>>> cv 65/149
	>>> cv 66/149
	>>> cv 67/149
	>>> cv 68/149
	>>> cv 69/149
	>>> cv 70/149
	>>> cv 71/149
	>>> cv 72/149
	>>> cv 73/149
	>>> cv 74/149
	>>> cv 75/149
	>>> cv 76/149
	>>> cv 77/149
	>>> cv 78/149
	>>> cv 79/149
	>>> cv 80/149
	>>> cv 81/149
	>>> cv 82/149
	>>> cv 83/149
	>>> cv 84/149
	>>> cv 85/149
	>>> cv 86/149
	>>> cv 87/149
	>>> cv 88/149
	>>> cv 89/149
	>>> cv 90/149
	>>> cv 91/149
	>>> cv 92/149
	>>> cv 93/149
	>>> cv 94/149
	>>> cv 95/149
	>>> cv 96/149
	>>> cv 97/149
	>>> cv 98/149
	>>> cv 99/149
	>>> cv 100/149
	>>> cv 101/149
	>>> cv 102/149
	>>> cv 103/149
	>>> cv 104/149
	>>> cv 105/149
	>>> cv 106/149
	>>> cv 107/149
	>>> cv 108/149
	>>> cv 109/149
	>>> cv 110/149
	>>> cv 111/149
	>>> cv 112/149
	>>> cv 113/149
	>>> cv 114/149
	>>> cv 115/149
	>>> cv 116/149
	>>> cv 117/149
	>>> cv 118/149
	>>> cv 119/149
	>>> cv 120/149
	>>> cv 121/149
	>>> cv 122/149
	>>> cv 123/149
	>>> cv 124/149
	>>> cv 125/149
	>>> cv 126/149
	>>> cv 127/149
	>>> cv 128/149
	>>> cv 129/149
	>>> cv 130/149
	>>> cv 131/149
	>>> cv 132/149
	>>> cv 133/149
	>>> cv 134/149
	>>> cv 135/149
	>>> cv 136/149
	>>> cv 137/149
	>>> cv 138/149
	>>> cv 139/149
	>>> cv 140/149
	>>> cv 141/149
	>>> cv 142/149
	>>> cv 143/149
	>>> cv 144/149
	>>> cv 145/149
	>>> cv 146/149
	>>> cv 147/149
	>>> cv 148/149
	>>> cv 149/149
(4/48) | Normalize = True | {'adaptive': True, 'bandwidth': 'scott', 'kernel': 'epanechnikov'}
	>>> cv 1/149
	>>> cv 2/149
	>>> cv 3/149
	>>> cv 4/149
	>>> cv 5/149
	>>> cv 6/149
	>>> cv 7/149
	>>> cv 8/149
	>>> cv 9/149
	>>> cv 10/149
	>>> cv 11/149
	>>> cv 12/149
	>>> cv 13/149
	>>> cv 14/149
	>>> cv 15/149
	>>> cv 16/149
	>>> cv 17/149
	>>> cv 18/149
	>>> cv 19/149
	>>> cv 20/149
	>>> cv 21/149
	>>> cv 22/149
	>>> cv 23/149
	>>> cv 24/149
	>>> cv 25/149
	>>> cv 26/149
	>>> cv 27/149
	>>> cv 28/149
	>>> cv 29/149
	>>> cv 30/149
	>>> cv 31/149
	>>> cv 32/149
	>>> cv 33/149
	>>> cv 34/149
	>>> cv 35/149
	>>> cv 36/149
	>>> cv 37/149
	>>> cv 38/149
	>>> cv 39/149
	>>> cv 40/149
	>>> cv 41/149
	>>> cv 42/149
	>>> cv 43/149
	>>> cv 44/149
	>>> cv 45/149
	>>> cv 46/149
	>>> cv 47/149
	>>> cv 48/149
	>>> cv 49/149
	>>> cv 50/149
	>>> cv 51/149
	>>> cv 52/149
	>>> cv 53/149
	>>> cv 54/149
	>>> cv 55/149
	>>> cv 56/149
	>>> cv 57/149
	>>> cv 58/149
	>>> cv 59/149
	>>> cv 60/149
	>>> cv 61/149
	>>> cv 62/149
	>>> cv 63/149
	>>> cv 64/149
	>>> cv 65/149
	>>> cv 66/149
	>>> cv 67/149
	>>> cv 68/149
	>>> cv 69/149
	>>> cv 70/149
	>>> cv 71/149
	>>> cv 72/149
	>>> cv 73/149
	>>> cv 74/149
	>>> cv 75/149
	>>> cv 76/149
	>>> cv 77/149
	>>> cv 78/149
	>>> cv 79/149
	>>> cv 80/149
	>>> cv 81/149
	>>> cv 82/149
	>>> cv 83/149
	>>> cv 84/149
	>>> cv 85/149
	>>> cv 86/149
	>>> cv 87/149
	>>> cv 88/149
	>>> cv 89/149
	>>> cv 90/149
	>>> cv 91/149
	>>> cv 92/149
	>>> cv 93/149
	>>> cv 94/149
	>>> cv 95/149
	>>> cv 96/149
	>>> cv 97/149
	>>> cv 98/149
	>>> cv 99/149
	>>> cv 100/149
	>>> cv 101/149
	>>> cv 102/149
	>>> cv 103/149
	>>> cv 104/149
	>>> cv 105/149
	>>> cv 106/149
	>>> cv 107/149
	>>> cv 108/149
	>>> cv 109/149
	>>> cv 110/149
	>>> cv 111/149
	>>> cv 112/149
	>>> cv 113/149
	>>> cv 114/149
	>>> cv 115/149
	>>> cv 116/149
	>>> cv 117/149
	>>> cv 118/149
	>>> cv 119/149
	>>> cv 120/149
	>>> cv 121/149
	>>> cv 122/149
	>>> cv 123/149
	>>> cv 124/149
	>>> cv 125/149
	>>> cv 126/149
	>>> cv 127/149
	>>> cv 128/149
	>>> cv 129/149
	>>> cv 130/149
	>>> cv 131/149
	>>> cv 132/149
	>>> cv 133/149
	>>> cv 134/149
	>>> cv 135/149
	>>> cv 136/149
	>>> cv 137/149
	>>> cv 138/149
	>>> cv 139/149
	>>> cv 140/149
	>>> cv 141/149
	>>> cv 142/149
	>>> cv 143/149
	>>> cv 144/149
	>>> cv 145/149
	>>> cv 146/149
	>>> cv 147/149
	>>> cv 148/149
	>>> cv 149/149
(5/48) | Normalize = True | {'adaptive': False, 'bandwidth': 'silverman', 'kernel': 'gaussian'}
	>>> cv 1/149
	 ERROR: Array must not contain infs or NaNs
(6/48) | Normalize = True | {'adaptive': False, 'bandwidth': 'silverman', 'kernel': 'epanechnikov'}
	>>> cv 1/149
	 ERROR: Array must not contain infs or NaNs
(7/48) | Normalize = True | {'adaptive': False, 'bandwidth': 'scott', 'kernel': 'gaussian'}
	>>> cv 1/149
	 ERROR: Array must not contain infs or NaNs
(8/48) | Normalize = True | {'adaptive': False, 'bandwidth': 'scott', 'kernel': 'epanechnikov'}
	>>> cv 1/149
	>>> cv 2/149
	>>> cv 3/149
	>>> cv 4/149
	>>> cv 5/149
	>>> cv 6/149
	>>> cv 7/149
	>>> cv 8/149
	>>> cv 9/149
	>>> cv 10/149
	>>> cv 11/149
	>>> cv 12/149
	>>> cv 13/149
	>>> cv 14/149
	>>> cv 15/149
	>>> cv 16/149
	>>> cv 17/149
	>>> cv 18/149
	>>> cv 19/149
	>>> cv 20/149
	>>> cv 21/149
	>>> cv 22/149
	>>> cv 23/149
	>>> cv 24/149
	>>> cv 25/149
	>>> cv 26/149
	>>> cv 27/149
	>>> cv 28/149
	>>> cv 29/149
	>>> cv 30/149
	>>> cv 31/149
	>>> cv 32/149
	>>> cv 33/149
	>>> cv 34/149
	>>> cv 35/149
	>>> cv 36/149
	>>> cv 37/149
	>>> cv 38/149
	>>> cv 39/149
	>>> cv 40/149
	>>> cv 41/149
	>>> cv 42/149
	>>> cv 43/149
	>>> cv 44/149
	>>> cv 45/149
	>>> cv 46/149
	>>> cv 47/149
	>>> cv 48/149
	>>> cv 49/149
	>>> cv 50/149
	>>> cv 51/149
	>>> cv 52/149
	>>> cv 53/149
	>>> cv 54/149
	>>> cv 55/149
	>>> cv 56/149
	>>> cv 57/149
	>>> cv 58/149
	>>> cv 59/149
	>>> cv 60/149
	>>> cv 61/149
	>>> cv 62/149
	>>> cv 63/149
	>>> cv 64/149
	>>> cv 65/149
	>>> cv 66/149
	>>> cv 67/149
	>>> cv 68/149
	>>> cv 69/149
	>>> cv 70/149
	>>> cv 71/149
	>>> cv 72/149
	>>> cv 73/149
	>>> cv 74/149
	>>> cv 75/149
	>>> cv 76/149
	>>> cv 77/149
	>>> cv 78/149
	>>> cv 79/149
	>>> cv 80/149
	>>> cv 81/149
	>>> cv 82/149
	>>> cv 83/149
	>>> cv 84/149
	>>> cv 85/149
	>>> cv 86/149
	>>> cv 87/149
	>>> cv 88/149
	>>> cv 89/149
	>>> cv 90/149
	>>> cv 91/149
	>>> cv 92/149
	>>> cv 93/149
	>>> cv 94/149
	>>> cv 95/149
	>>> cv 96/149
	>>> cv 97/149
	>>> cv 98/149
	>>> cv 99/149
	>>> cv 100/149
	>>> cv 101/149
	>>> cv 102/149
	>>> cv 103/149
	>>> cv 104/149
	>>> cv 105/149
	>>> cv 106/149
	>>> cv 107/149
	>>> cv 108/149
	>>> cv 109/149
	>>> cv 110/149
	>>> cv 111/149
	>>> cv 112/149
	>>> cv 113/149
	>>> cv 114/149
	>>> cv 115/149
	>>> cv 116/149
	>>> cv 117/149
	>>> cv 118/149
	>>> cv 119/149
	>>> cv 120/149
	>>> cv 121/149
	>>> cv 122/149
	>>> cv 123/149
	>>> cv 124/149
	>>> cv 125/149
	>>> cv 126/149
	>>> cv 127/149
	>>> cv 128/149
	>>> cv 129/149
	>>> cv 130/149
	>>> cv 131/149
	>>> cv 132/149
	>>> cv 133/149
	>>> cv 134/149
	>>> cv 135/149
	>>> cv 136/149
	>>> cv 137/149
	>>> cv 138/149
	>>> cv 139/149
	>>> cv 140/149
	>>> cv 141/149
	>>> cv 142/149
	>>> cv 143/149
	>>> cv 144/149
	>>> cv 145/149
	>>> cv 146/149
	>>> cv 147/149
	>>> cv 148/149
	>>> cv 149/149
(9/48) | Normalize = True | {'adaptive': True, 'bandwidth': 'silverman', 'df': 2, 'kernel': 't_student'}
	>>> cv 1/149
	>>> cv 2/149
	>>> cv 3/149
	>>> cv 4/149
	>>> cv 5/149
	>>> cv 6/149
	>>> cv 7/149
	>>> cv 8/149
	>>> cv 9/149
	>>> cv 10/149
	>>> cv 11/149
	>>> cv 12/149
	>>> cv 13/149
	>>> cv 14/149
	>>> cv 15/149
	>>> cv 16/149
	>>> cv 17/149
	>>> cv 18/149
	>>> cv 19/149
	>>> cv 20/149
	>>> cv 21/149
	>>> cv 22/149
	>>> cv 23/149
	>>> cv 24/149
	>>> cv 25/149
	>>> cv 26/149
	>>> cv 27/149
	>>> cv 28/149
	>>> cv 29/149
	>>> cv 30/149
	>>> cv 31/149
	>>> cv 32/149
	>>> cv 33/149
	>>> cv 34/149
	>>> cv 35/149
	>>> cv 36/149
	>>> cv 37/149
	>>> cv 38/149
	>>> cv 39/149
	>>> cv 40/149
	>>> cv 41/149
	>>> cv 42/149
	>>> cv 43/149
	>>> cv 44/149
	>>> cv 45/149
	>>> cv 46/149
	>>> cv 47/149
	>>> cv 48/149
	>>> cv 49/149
	>>> cv 50/149
	>>> cv 51/149
	>>> cv 52/149
	>>> cv 53/149
	>>> cv 54/149
	>>> cv 55/149
	>>> cv 56/149
	>>> cv 57/149
	>>> cv 58/149
	>>> cv 59/149
	>>> cv 60/149
	>>> cv 61/149
	>>> cv 62/149
	>>> cv 63/149
	>>> cv 64/149
	>>> cv 65/149
	>>> cv 66/149
	>>> cv 67/149
Number of selected lags is zero. Forecast with mean.
	>>> cv 68/149
	>>> cv 69/149
	>>> cv 70/149
	>>> cv 71/149
	>>> cv 72/149
	>>> cv 73/149
	>>> cv 74/149
	>>> cv 75/149
	>>> cv 76/149
	>>> cv 77/149
	>>> cv 78/149
	>>> cv 79/149
	>>> cv 80/149
	>>> cv 81/149
	>>> cv 82/149
	>>> cv 83/149
	>>> cv 84/149
	>>> cv 85/149
	>>> cv 86/149
	>>> cv 87/149
	>>> cv 88/149
	>>> cv 89/149
	>>> cv 90/149
	>>> cv 91/149
	>>> cv 92/149
	>>> cv 93/149
	>>> cv 94/149
	>>> cv 95/149
	>>> cv 96/149
	>>> cv 97/149
	>>> cv 98/149
	>>> cv 99/149
	>>> cv 100/149
	>>> cv 101/149
	>>> cv 102/149
	>>> cv 103/149
	>>> cv 104/149
	>>> cv 105/149
	>>> cv 106/149
	>>> cv 107/149
	>>> cv 108/149
	>>> cv 109/149
	>>> cv 110/149
	>>> cv 111/149
	>>> cv 112/149
	>>> cv 113/149
	>>> cv 114/149
	>>> cv 115/149
	>>> cv 116/149
	>>> cv 117/149
	>>> cv 118/149
	>>> cv 119/149
	>>> cv 120/149
	>>> cv 121/149
	>>> cv 122/149
	>>> cv 123/149
	>>> cv 124/149
	>>> cv 125/149
	>>> cv 126/149
	>>> cv 127/149
	>>> cv 128/149
	>>> cv 129/149
	>>> cv 130/149
	>>> cv 131/149
	>>> cv 132/149
	>>> cv 133/149
	>>> cv 134/149
	>>> cv 135/149
	>>> cv 136/149
	>>> cv 137/149
	>>> cv 138/149
	>>> cv 139/149
	>>> cv 140/149
	>>> cv 141/149
	>>> cv 142/149
	>>> cv 143/149
	>>> cv 144/149
	>>> cv 145/149
	>>> cv 146/149
	>>> cv 147/149
	>>> cv 148/149
	>>> cv 149/149
(10/48) | Normalize = True | {'adaptive': True, 'bandwidth': 'silverman', 'df': 3, 'kernel': 't_student'}
	>>> cv 1/149
	>>> cv 2/149
	>>> cv 3/149
	>>> cv 4/149
	>>> cv 5/149
	>>> cv 6/149
	>>> cv 7/149
	>>> cv 8/149
	>>> cv 9/149
	>>> cv 10/149
	>>> cv 11/149
	>>> cv 12/149
	>>> cv 13/149
	>>> cv 14/149
	>>> cv 15/149
	>>> cv 16/149
	>>> cv 17/149
	>>> cv 18/149
	>>> cv 19/149
	>>> cv 20/149
	>>> cv 21/149
	>>> cv 22/149
	>>> cv 23/149
	>>> cv 24/149
	>>> cv 25/149
	>>> cv 26/149
	>>> cv 27/149
	>>> cv 28/149
	>>> cv 29/149
	>>> cv 30/149
	>>> cv 31/149
	>>> cv 32/149
	>>> cv 33/149
	>>> cv 34/149
	>>> cv 35/149
	>>> cv 36/149
	>>> cv 37/149
	>>> cv 38/149
	>>> cv 39/149
	>>> cv 40/149
	>>> cv 41/149
	>>> cv 42/149
	>>> cv 43/149
	>>> cv 44/149
	>>> cv 45/149
	>>> cv 46/149
	>>> cv 47/149
	>>> cv 48/149
	>>> cv 49/149
	>>> cv 50/149
	>>> cv 51/149
	>>> cv 52/149
	>>> cv 53/149
	>>> cv 54/149
	>>> cv 55/149
	>>> cv 56/149
	>>> cv 57/149
	>>> cv 58/149
	>>> cv 59/149
	>>> cv 60/149
	>>> cv 61/149
	>>> cv 62/149
	>>> cv 63/149
	>>> cv 64/149
	>>> cv 65/149
	>>> cv 66/149
	>>> cv 67/149
Number of selected lags is zero. Forecast with mean.
	>>> cv 68/149
	>>> cv 69/149
	>>> cv 70/149
	>>> cv 71/149
	>>> cv 72/149
	>>> cv 73/149
	>>> cv 74/149
	>>> cv 75/149
	>>> cv 76/149
	>>> cv 77/149
	>>> cv 78/149
	>>> cv 79/149
	>>> cv 80/149
	>>> cv 81/149
	>>> cv 82/149
	>>> cv 83/149
	>>> cv 84/149
	>>> cv 85/149
	>>> cv 86/149
	>>> cv 87/149
	>>> cv 88/149
	>>> cv 89/149
	>>> cv 90/149
	>>> cv 91/149
	>>> cv 92/149
	>>> cv 93/149
	>>> cv 94/149
	>>> cv 95/149
	>>> cv 96/149
	>>> cv 97/149
	>>> cv 98/149
	>>> cv 99/149
	>>> cv 100/149
	>>> cv 101/149
	>>> cv 102/149
	>>> cv 103/149
	>>> cv 104/149
	>>> cv 105/149
	>>> cv 106/149
	>>> cv 107/149
	>>> cv 108/149
	>>> cv 109/149
	>>> cv 110/149
	>>> cv 111/149
	>>> cv 112/149
	>>> cv 113/149
	>>> cv 114/149
	>>> cv 115/149
	>>> cv 116/149
	>>> cv 117/149
	>>> cv 118/149
	>>> cv 119/149
	>>> cv 120/149
	>>> cv 121/149
	>>> cv 122/149
	>>> cv 123/149
	>>> cv 124/149
	>>> cv 125/149
	>>> cv 126/149
	>>> cv 127/149
	>>> cv 128/149
	>>> cv 129/149
	>>> cv 130/149
	>>> cv 131/149
	>>> cv 132/149
	>>> cv 133/149
	>>> cv 134/149
	>>> cv 135/149
	>>> cv 136/149
	>>> cv 137/149
	>>> cv 138/149
	>>> cv 139/149
	>>> cv 140/149
	>>> cv 141/149
	>>> cv 142/149
	>>> cv 143/149
	>>> cv 144/149
	>>> cv 145/149
	>>> cv 146/149
	>>> cv 147/149
	>>> cv 148/149
	>>> cv 149/149
(11/48) | Normalize = True | {'adaptive': True, 'bandwidth': 'silverman', 'df': 4, 'kernel': 't_student'}
	>>> cv 1/149
	>>> cv 2/149
	>>> cv 3/149
	>>> cv 4/149
	>>> cv 5/149
	>>> cv 6/149
	>>> cv 7/149
	>>> cv 8/149
	>>> cv 9/149
	>>> cv 10/149
	>>> cv 11/149
	>>> cv 12/149
	>>> cv 13/149
	>>> cv 14/149
	>>> cv 15/149
	>>> cv 16/149
	>>> cv 17/149
	>>> cv 18/149
	>>> cv 19/149
	>>> cv 20/149
	>>> cv 21/149
	>>> cv 22/149
	>>> cv 23/149
	>>> cv 24/149
	>>> cv 25/149
	>>> cv 26/149
	>>> cv 27/149
	>>> cv 28/149
	>>> cv 29/149
	>>> cv 30/149
	>>> cv 31/149
	>>> cv 32/149
	>>> cv 33/149
	>>> cv 34/149
	>>> cv 35/149
	>>> cv 36/149
	>>> cv 37/149
	>>> cv 38/149
	>>> cv 39/149
	>>> cv 40/149
	>>> cv 41/149
	>>> cv 42/149
	>>> cv 43/149
	>>> cv 44/149
	>>> cv 45/149
	>>> cv 46/149
	>>> cv 47/149
	>>> cv 48/149
	>>> cv 49/149
	>>> cv 50/149
	>>> cv 51/149
	>>> cv 52/149
	>>> cv 53/149
	>>> cv 54/149
	>>> cv 55/149
	>>> cv 56/149
	>>> cv 57/149
	>>> cv 58/149
	>>> cv 59/149
	>>> cv 60/149
	>>> cv 61/149
	>>> cv 62/149
	>>> cv 63/149
	>>> cv 64/149
	>>> cv 65/149
	>>> cv 66/149
	>>> cv 67/149
Number of selected lags is zero. Forecast with mean.
	>>> cv 68/149
	>>> cv 69/149
	>>> cv 70/149
	>>> cv 71/149
	>>> cv 72/149
	>>> cv 73/149
	>>> cv 74/149
	>>> cv 75/149
	>>> cv 76/149
	>>> cv 77/149
	>>> cv 78/149
	>>> cv 79/149
	>>> cv 80/149
	>>> cv 81/149
	>>> cv 82/149
	>>> cv 83/149
	>>> cv 84/149
	>>> cv 85/149
	>>> cv 86/149
	>>> cv 87/149
	>>> cv 88/149
	>>> cv 89/149
	>>> cv 90/149
	>>> cv 91/149
	>>> cv 92/149
	>>> cv 93/149
	>>> cv 94/149
	>>> cv 95/149
	>>> cv 96/149
	>>> cv 97/149
	>>> cv 98/149
	>>> cv 99/149
	>>> cv 100/149
	>>> cv 101/149
	>>> cv 102/149
	>>> cv 103/149
	>>> cv 104/149
	>>> cv 105/149
	>>> cv 106/149
	>>> cv 107/149
	>>> cv 108/149
	>>> cv 109/149
	>>> cv 110/149
	>>> cv 111/149
	>>> cv 112/149
	>>> cv 113/149
	>>> cv 114/149
	>>> cv 115/149
	>>> cv 116/149
	>>> cv 117/149
	>>> cv 118/149
	>>> cv 119/149
	>>> cv 120/149
	>>> cv 121/149
	>>> cv 122/149
	>>> cv 123/149
	>>> cv 124/149
	>>> cv 125/149
	>>> cv 126/149
	>>> cv 127/149
	>>> cv 128/149
	>>> cv 129/149
	>>> cv 130/149
	>>> cv 131/149
	>>> cv 132/149
	>>> cv 133/149
	>>> cv 134/149
	>>> cv 135/149
	>>> cv 136/149
	>>> cv 137/149
	>>> cv 138/149
	>>> cv 139/149
	>>> cv 140/149
	>>> cv 141/149
	>>> cv 142/149
	>>> cv 143/149
	>>> cv 144/149
	>>> cv 145/149
	>>> cv 146/149
	>>> cv 147/149
	>>> cv 148/149
	>>> cv 149/149
(12/48) | Normalize = True | {'adaptive': True, 'bandwidth': 'silverman', 'df': 5, 'kernel': 't_student'}
	>>> cv 1/149
	>>> cv 2/149
	>>> cv 3/149
	>>> cv 4/149
	>>> cv 5/149
	>>> cv 6/149
	>>> cv 7/149
	>>> cv 8/149
	>>> cv 9/149
	>>> cv 10/149
	>>> cv 11/149
	>>> cv 12/149
	>>> cv 13/149
	>>> cv 14/149
	>>> cv 15/149
	>>> cv 16/149
	>>> cv 17/149
	>>> cv 18/149
	>>> cv 19/149
	>>> cv 20/149
	>>> cv 21/149
	>>> cv 22/149
	>>> cv 23/149
	>>> cv 24/149
	>>> cv 25/149
	>>> cv 26/149
	>>> cv 27/149
	>>> cv 28/149
	>>> cv 29/149
	>>> cv 30/149
	>>> cv 31/149
	>>> cv 32/149
	>>> cv 33/149
	>>> cv 34/149
	>>> cv 35/149
	>>> cv 36/149
	>>> cv 37/149
	>>> cv 38/149
	>>> cv 39/149
	>>> cv 40/149
	>>> cv 41/149
	>>> cv 42/149
	>>> cv 43/149
	>>> cv 44/149
	>>> cv 45/149
	>>> cv 46/149
	>>> cv 47/149
	>>> cv 48/149
	>>> cv 49/149
	>>> cv 50/149
	>>> cv 51/149
	>>> cv 52/149
	>>> cv 53/149
	>>> cv 54/149
	>>> cv 55/149
	>>> cv 56/149
	>>> cv 57/149
	>>> cv 58/149
	>>> cv 59/149
	>>> cv 60/149
	>>> cv 61/149
	>>> cv 62/149
	>>> cv 63/149
	>>> cv 64/149
	>>> cv 65/149
	>>> cv 66/149
	>>> cv 67/149
Number of selected lags is zero. Forecast with mean.
	>>> cv 68/149
	>>> cv 69/149
	>>> cv 70/149
	>>> cv 71/149
	>>> cv 72/149
	>>> cv 73/149
	>>> cv 74/149
	>>> cv 75/149
	>>> cv 76/149
	>>> cv 77/149
	>>> cv 78/149
	>>> cv 79/149
	>>> cv 80/149
	>>> cv 81/149
	>>> cv 82/149
	>>> cv 83/149
	>>> cv 84/149
	>>> cv 85/149
	>>> cv 86/149
	>>> cv 87/149
	>>> cv 88/149
	>>> cv 89/149
	>>> cv 90/149
	>>> cv 91/149
	>>> cv 92/149
	>>> cv 93/149
	>>> cv 94/149
	>>> cv 95/149
	>>> cv 96/149
	>>> cv 97/149
	>>> cv 98/149
	>>> cv 99/149
	>>> cv 100/149
	>>> cv 101/149
	>>> cv 102/149
	>>> cv 103/149
	>>> cv 104/149
	>>> cv 105/149
	>>> cv 106/149
	>>> cv 107/149
	>>> cv 108/149
	>>> cv 109/149
	>>> cv 110/149
	>>> cv 111/149
	>>> cv 112/149
	>>> cv 113/149
	>>> cv 114/149
	>>> cv 115/149
	>>> cv 116/149
	>>> cv 117/149
	>>> cv 118/149
	>>> cv 119/149
	>>> cv 120/149
	>>> cv 121/149
	>>> cv 122/149
	>>> cv 123/149
	>>> cv 124/149
	>>> cv 125/149
	>>> cv 126/149
	>>> cv 127/149
	>>> cv 128/149
	>>> cv 129/149
	>>> cv 130/149
	>>> cv 131/149
	>>> cv 132/149
	>>> cv 133/149
	>>> cv 134/149
	>>> cv 135/149
	>>> cv 136/149
	>>> cv 137/149
	>>> cv 138/149
	>>> cv 139/149
	>>> cv 140/149
	>>> cv 141/149
	>>> cv 142/149
	>>> cv 143/149
	>>> cv 144/149
	>>> cv 145/149
	>>> cv 146/149
	>>> cv 147/149
	>>> cv 148/149
	>>> cv 149/149
(13/48) | Normalize = True | {'adaptive': True, 'bandwidth': 'scott', 'df': 2, 'kernel': 't_student'}
	>>> cv 1/149
	>>> cv 2/149
	>>> cv 3/149
	>>> cv 4/149
	>>> cv 5/149
	>>> cv 6/149
	>>> cv 7/149
	>>> cv 8/149
	>>> cv 9/149
	>>> cv 10/149
	>>> cv 11/149
	>>> cv 12/149
	>>> cv 13/149
	>>> cv 14/149
	>>> cv 15/149
	>>> cv 16/149
	>>> cv 17/149
	>>> cv 18/149
	>>> cv 19/149
	>>> cv 20/149
	>>> cv 21/149
	>>> cv 22/149
	>>> cv 23/149
	>>> cv 24/149
	>>> cv 25/149
	>>> cv 26/149
	>>> cv 27/149
	>>> cv 28/149
	>>> cv 29/149
	>>> cv 30/149
	>>> cv 31/149
	>>> cv 32/149
	>>> cv 33/149
	>>> cv 34/149
	>>> cv 35/149
	>>> cv 36/149
	>>> cv 37/149
	>>> cv 38/149
	>>> cv 39/149
	>>> cv 40/149
	>>> cv 41/149
	>>> cv 42/149
	>>> cv 43/149
	>>> cv 44/149
	>>> cv 45/149
	>>> cv 46/149
	>>> cv 47/149
	>>> cv 48/149
	>>> cv 49/149
	>>> cv 50/149
	>>> cv 51/149
	>>> cv 52/149
	>>> cv 53/149
	>>> cv 54/149
	>>> cv 55/149
	>>> cv 56/149
	>>> cv 57/149
	>>> cv 58/149
	>>> cv 59/149
	>>> cv 60/149
	>>> cv 61/149
	>>> cv 62/149
	>>> cv 63/149
	>>> cv 64/149
	>>> cv 65/149
	>>> cv 66/149
	>>> cv 67/149
	>>> cv 68/149
	>>> cv 69/149
	>>> cv 70/149
	>>> cv 71/149
	>>> cv 72/149
	>>> cv 73/149
	>>> cv 74/149
	>>> cv 75/149
	>>> cv 76/149
	>>> cv 77/149
	>>> cv 78/149
	>>> cv 79/149
	>>> cv 80/149
	>>> cv 81/149
	>>> cv 82/149
	>>> cv 83/149
	>>> cv 84/149
	>>> cv 85/149
	>>> cv 86/149
	>>> cv 87/149
	>>> cv 88/149
	>>> cv 89/149
	>>> cv 90/149
	>>> cv 91/149
	>>> cv 92/149
	>>> cv 93/149
	>>> cv 94/149
	>>> cv 95/149
	>>> cv 96/149
	>>> cv 97/149
	>>> cv 98/149
	>>> cv 99/149
	>>> cv 100/149
	>>> cv 101/149
	>>> cv 102/149
	>>> cv 103/149
	>>> cv 104/149
	>>> cv 105/149
	>>> cv 106/149
	>>> cv 107/149
	>>> cv 108/149
	>>> cv 109/149
	>>> cv 110/149
	>>> cv 111/149
	>>> cv 112/149
	>>> cv 113/149
	>>> cv 114/149
	>>> cv 115/149
	>>> cv 116/149
	>>> cv 117/149
	>>> cv 118/149
	>>> cv 119/149
	>>> cv 120/149
	>>> cv 121/149
	>>> cv 122/149
	>>> cv 123/149
	>>> cv 124/149
	>>> cv 125/149
	>>> cv 126/149
	>>> cv 127/149
	>>> cv 128/149
	>>> cv 129/149
	>>> cv 130/149
	>>> cv 131/149
	>>> cv 132/149
	>>> cv 133/149
	>>> cv 134/149
	>>> cv 135/149
	>>> cv 136/149
	>>> cv 137/149
	>>> cv 138/149
	>>> cv 139/149
	>>> cv 140/149
	>>> cv 141/149
	>>> cv 142/149
	>>> cv 143/149
	>>> cv 144/149
	>>> cv 145/149
	>>> cv 146/149
	>>> cv 147/149
	>>> cv 148/149

In [18]:
results_df.to_excel("../data/processed/cv_density_estimation_v2.xlsx", index=False)

In [27]:
# RESULTS BY MODEL
metrics = ["KLD", "JSD", "L_1", "L_2", "L_INFTY"]

mean_df = (
    results_df
    .groupby(['normalized_density', 'kernel', 'bandwidth',	'adaptive',	'method'])[metrics]
    .mean()
    .reset_index()
)
mean_df

,normalized_density,kernel,bandwidth,adaptive,method,KLD,JSD,L_1,L_2,L_INFTY
0,False,epanechnikov,scott,False,KLE,0.564823,0.010489,32878.650277,1760.368562,209.094657
1,False,epanechnikov,scott,True,KLE,0.229213,0.008642,31566.961246,1832.049633,249.345988
2,False,gaussian,scott,True,KLE,0.128304,0.005878,25448.966773,1363.193503,157.155147
3,False,t_student,scott,False,KLE,0.136366,0.005914,23196.732773,1132.757191,118.313098
4,False,t_student,scott,True,KLE,0.086657,0.005219,22094.973669,1198.394264,145.108980
5,False,t_student,silverman,False,KLE,0.225297,0.008554,28815.590965,1536.645414,201.274973
6,False,t_student,silverman,True,KLE,0.132109,0.007325,26917.456066,1654.699385,277.771804
7,True,epanechnikov,scott,False,KLE,0.094531,0.003846,19848.571186,1449.514707,205.825519
8,True,epanechnikov,scott,True,KLE,0.061142,0.004331,21160.892721,1684.452932,261.591930
9,True,gaussian,scott,True,KLE,0.036903,0.002505,15318.026892,1090.001149,143.604863
10,True,t_student,scott,False,KLE,0.033641,0.002037,13435.537880,838.789978,99.724172
11,True,t_student,scott,True,KLE,0.033303,0.002278,14686.849557,1013.175067,134.154399
12,True,t_student,silverman,False,KLE,0.056458,0.003548,17307.877606,1269.510784,204.979762
13,True,t_student,silverman,True,KLE,0.060691,0.004281,19731.586071,1633.588032,335.153535

In [35]:
# BEST METHOD
for m in metrics:
    best_value = mean_df[m].min()
    mean_df[f"win_{m}"] = mean_df[m] == best_value

win_cols = [f"win_{m}" for m in metrics]

mean_df["n_wins"] = mean_df[win_cols].sum(axis=1)

best_overall = mean_df.sort_values("n_wins", ascending=False)

print(best_overall.head(3))

print('n')
print("Best method:", best_overall.iloc[0])

    normalized_density        kernel bandwidth  adaptive method       KLD  \
10                True     t_student     scott     False    KLE  0.033641
11                True     t_student     scott      True    KLE  0.033303
0                False  epanechnikov     scott     False    KLE  0.564823

         JSD           L_1          L_2     L_INFTY  win_KLD  win_JSD  \
10  0.002037  13435.537880   838.789978   99.724172    False     True
11  0.002278  14686.849557  1013.175067  134.154399     True    False
0   0.010489  32878.650277  1760.368562  209.094657    False    False

    win_L_1  win_L_2  win_L_INFTY  n_wins
10     True     True         True       4
11    False    False        False       1
0     False    False        False       0
n
Best method: normalized_density           True
kernel                  t_student
bandwidth                   scott
adaptive                    False
method                        KLE
KLD                      0.033641
JSD                      0.002037
L_1                   13435.53788
L_2                    838.789978
L_INFTY                 99.724172
win_KLD                     False
win_JSD                      True
win_L_1                      True
win_L_2                      True
win_L_INFTY                  True
n_wins                          4
Name: 10, dtype: object

In [36]:
# WINNER BY COUNT OF MIN ERROR BY FOLD
winners = (
    results_df
    .loc[results_df.groupby("fold")["JSD"].idxmin()]
    .value_counts(['normalized_density', 'kernel', 'bandwidth',	'adaptive',	'method'])
)

winners.reset_index()

   normalized_density        kernel  bandwidth  adaptive method  count
0                True     t_student      scott     False    KLE     80
1                True     t_student      scott      True    KLE     23
2                True     t_student  silverman     False    KLE     19
3                True     t_student  silverman      True    KLE     12
4                True      gaussian      scott      True    KLE     10
5                True  epanechnikov      scott     False    KLE      2
6                True  epanechnikov      scott      True    KLE      1
7               False     t_student      scott     False    KLE      1
8               False     t_student      scott      True    KLE      1

# Checking models with error