In [1]:
import numpy as np
import pandas as pd

tables_path = "../../data/processed/"
out_path    = "../../../densities4risk_doc/Tables/"

# Cross validation

In [ ]:
cv_results = pd.read_excel('/'.join([tables_path, 'cv/20260225/','cv_density_forecasting_20260224.xlsx']))
cv_results = cv_results[['normalized_density', 'bandwidth', 'kernel', 'robust_std', #'dFPC_dimensions',
                          'KLD', 'JSD', 'L_1', 'L_2', 'L_INFTY']]
cv_results_summary = cv_results.groupby(['normalized_density', 'bandwidth', 'kernel', 'robust_std'], as_index=False).mean()
cv_results.sort_values(by="KLD")

,normalized_density,kde_params,bandwidth,kernel,robust_std,dFPC_dimensions,fold,KLD,JSD,L_1,L_2,L_INFTY
0,True,rot_gaussian_robust,rot,gaussian,robust,2,1,0.051251,0.002685,15222.842474,911.815994,92.487038
1,True,rot_gaussian_robust,rot,gaussian,robust,2,2,0.017890,0.000801,10501.183031,740.873613,80.832096
2,True,rot_gaussian_robust,rot,gaussian,robust,2,3,0.011463,0.000354,6667.423117,449.015354,58.640618
3,True,rot_gaussian_robust,rot,gaussian,robust,2,4,0.032898,0.001005,11219.581091,682.585770,80.803197
4,True,rot_gaussian_robust,rot,gaussian,robust,2,5,0.080247,0.006256,30851.789739,2357.599314,368.999369
...,...,...,...,...,...,...,...,...,...,...,...,...
22045,False,adaptive_t-student | df=5,adaptive,t-student | df=5,False,6,143,0.079766,0.006357,29029.395303,1698.613958,199.044319
22046,False,adaptive_t-student | df=5,adaptive,t-student | df=5,False,6,144,0.085014,0.005041,26607.272491,1410.487742,175.568254
22047,False,adaptive_t-student | df=5,adaptive,t-student | df=5,False,6,145,0.118852,0.007303,32597.714285,1961.712334,255.903416
22048,False,adaptive_t-student | df=5,adaptive,t-student | df=5,False,6,146,0.522323,0.034294,73598.008425,4666.280668,655.004746
22049,False,adaptive_t-student | df=5,adaptive,t-student | df=5,False,6,147,0.043164,0.002719,16646.487241,958.243578,95.287131

In [15]:
# cv_results = pd.read_excel('/'.join([tables_path, 'cv_density_estimation_v3.xlsx']))#.drop(columns=["Unnamed: 0"])
cv_results = pd.read_excel('/'.join([tables_path, 'cv/20260225/','cv_density_forecasting_20260224.xlsx']))#.drop(columns=["Unnamed: 0"])

cv_results = cv_results[['normalized_density', 'bandwidth', 'kernel', 'robust_std', #'dFPC_dimensions',
                          'KLD', 'JSD', 'L_1', 'L_2', 'L_INFTY']]
cv_results_summary = cv_results.groupby(['normalized_density', 'bandwidth', 'kernel', 'robust_std'], as_index=False).mean()

cv_results_summary["robust_std"] = cv_results_summary["robust_std"].apply(lambda x: True if x == "robust" else False)
cv_results_summary["bandwidth"] = cv_results_summary["bandwidth"].apply(lambda x: "silverman" if x == "rot" else x)

# formatting
## rename columns
corresp_cols =  {
    "kernel": "Kernel",
    "bandwidth": "Bandwidth", 
    "adaptive":  "Adaptive bandwidth", 
    "normalized_density": "Normalized pdf", 
    "robust_std": "Robust $\hat{\sigma}$",
    # "dFPC_dimensions": "Dimensions",
    "L_1": "$L_1$", 
    "L_2": "$L_2$", 
    "L_INFTY": "$L_{\infty}$"
    }
cv_results_summary.rename(columns=corresp_cols, inplace=True)
## sort by metric
cv_results_summary.sort_values(by="KLD", inplace=True)
## ajdust index for viz
cv_results_summary.index = np.arange(1,cv_results_summary.shape[0]+1)
## adjust fild values
# cv_results_summary.loc[:, "kernel"] = cv_results_summary.loc[:, "Kernel"].str.replace("_df_", " + df=").str.replace("t_student", "t-student")
cv_results_summary = cv_results_summary.round(4)

cv_results_summary.head()

,Normalized pdf,Bandwidth,Kernel,Robust $\hat{\sigma}$,KLD,JSD,$L_1$,$L_2$,$L_{\infty}$
1,True,adaptive,t-student | df=2,False,0.0316,0.0022,14777.9613,1004.8754,132.7172
2,True,adaptive,t-student | df=3,False,0.0335,0.0023,15015.0877,1036.3795,136.9042
3,True,adaptive,t-student | df=4,False,0.0344,0.0023,15127.0112,1054.1131,139.3776
4,True,adaptive,t-student | df=5,False,0.0350,0.0024,15217.1969,1067.3168,141.2142
5,True,adaptive,gaussian,False,0.0380,0.0026,15878.5599,1141.9402,151.8332

In [46]:
formatted_cv_summary = (   
    cv_results_summary.iloc[:-2,:]
    .style.background_gradient(
        cmap="RdYlGn_r",   # green = low, red = high
        axis=0            # column-wise
    )
    .format(precision=4)
)
formatted_cv_summary

In [47]:
# formatted_cv_summary.hide(axis="index") \
formatted_cv_summary \
    .to_latex(
    buf     = '/'.join([out_path, "cv_results_code.tex"]),
    caption = "Results for expanding window cross-validation t+1 forecasts.",
    label   = "tab:cv_results",
    convert_css=True,
    # column_format="c", #* len(cv_results_summary.columns)
    hrules  = True
    )

In [55]:
# Get 3 best models with normalized densities

non_normd_df = cv_results_summary[cv_results_summary["Normalized pdf"]==False]
cv_results_summary_top = pd.concat([
                         cv_results_summary[cv_results_summary["Normalized pdf"]==True].head(3),
                         non_normd_df.head(5),
                         non_normd_df[non_normd_df["Bandwidth"]=="cross-validation"].head(1),
                         non_normd_df[non_normd_df["Robust $\hat{\sigma}$"]==True].head(1),
                         non_normd_df[non_normd_df["Bandwidth"]=="rot"].head(2),
                         non_normd_df[non_normd_df["Kernel"]=="gaussian"].head(2),
                         non_normd_df[non_normd_df["Kernel"]=="epanechnikov"].head(2)
                        ], axis=0) \
                        .drop_duplicates().sort_index()
cv_results_summary_top

,Normalized pdf,Bandwidth,Kernel,Robust $\hat{\sigma}$,KLD,JSD,$L_1$,$L_2$,$L_{\infty}$
1,True,adaptive,t-student | df=2,False,0.0316,0.0022,14777.9613,1004.8754,132.7172
2,True,adaptive,t-student | df=3,False,0.0335,0.0023,15015.0877,1036.3795,136.9042
3,True,adaptive,t-student | df=4,False,0.0344,0.0023,15127.0112,1054.1131,139.3776
10,False,adaptive,t-student | df=2,False,0.0726,0.0049,22264.6612,1182.5507,141.3651
14,False,adaptive,t-student | df=3,False,0.0975,0.0056,11611.5072,865.4304,149.5459
15,False,adaptive,t-student | df=5,False,0.1089,0.0057,24111.0918,1313.8418,156.6797
16,False,adaptive,t-student | df=4,False,0.1117,0.0057,19842.0883,1154.5437,154.6300
17,False,adaptive,gaussian,False,0.1301,0.0060,26269.2074,1437.3050,168.2858
18,False,cross-validation,t-student | df=2,False,0.1597,0.0094,17385.0599,1174.7939,191.0764
22,False,adaptive,epanechnikov,False,0.2517,0.0088,32567.0572,1896.1466,257.5470
23,False,silverman,epanechnikov,False,0.2834,0.0070,27038.9976,1343.8274,134.3901
26,False,silverman,epanechnikov,True,0.3391,0.0077,28558.9664,1483.5477,160.5182
28,False,cross-validation,gaussian,False,0.4122,0.0250,39702.0781,3400.1640,1253.9851

In [53]:
# Concatenates 10 best models with and without normalizing pdf.
# N_best_models = 10
# cv_results_summary_top = pd.concat(
#                         [cv_results_summary[cv_results_summary["Normalized pdf"]==True].head(N_best_models),
#                          cv_results_summary[cv_results_summary["Normalized pdf"]==False].head(N_best_models)
#                         ]
#                         ).reset_index(drop=True)
# cv_results_summary_top.index = cv_results_summary_top.index+1
# cv_results_summary_top

In [56]:
# top 20
cv_results_summary_top = (   
    cv_results_summary_top.style
    .background_gradient(
        cmap="RdYlGn_r",   # green = low, red = high
        axis=0            # column-wise
    )
    .format(precision=4)
    ) \
    # .hide(axis="index")
cv_results_summary_top

In [58]:
cv_results_summary_top \
    .to_latex(
    buf     = '/'.join([out_path, "cv_results_top_code.tex"]),
    caption = "Results for expanding window cross-validation t+1 forecasts.",
    label   = "tab:cv_results_top",
    convert_css=True,
    # column_format="c", #* len(cv_results_summary.columns)
    hrules  = True   
)

# KDE

In [12]:
kde_constants = [
    {
    "Kernel": "$K_{gauss}$",
    "Method": "Silverman",
    "Parameters":   "C(K) = 1.06",
    "Std estimator": "\{$\hat{\sigma}_t$, $\hat{\sigma}_t^{IQR}$\}"
    },      {
    "Kernel": "$K_{gauss}$",
    "Method": "Adaptive",
    "Parameters":   "-",
    "Std estimator": "\{$\hat{\sigma}_t$\}"
    },      {
    "Kernel": "$K_{gauss}$",
    "Method": "Cross-validation",
    "Parameters":   "-",
    "Std estimator": "\{$\hat{\sigma}_t$\}"
    },      {
    "Kernel": "$K_{gauss}$",
    "Method": "SJ",
    "Parameters":   "-",
    "Std estimator": "\{$\hat{\sigma}_t$\}"
    },      {
    "Kernel": "$K_{gauss}$",
    "Method": "ISJ",
    "Parameters":   "-",
    "Std estimator": "\{$\hat{\sigma}_t$\}"
    },      {
    "Kernel": "$K_{epan}$",
    "Method": "Silverman",
    "Parameters":   "C(K) = 2.34",
    "Std estimator": "\{$\hat{\sigma}_t$, $\hat{\sigma}_t^{IQR}$\}"
    },      {
    "Kernel": "$K_{epan}$",
    "Method": "Adaptive",
    "Parameters":   "-",
    "Std estimator": "\{$\hat{\sigma}_t$\}"
    },      {
    "Kernel": "$K_{epan}$",
    "Method": "Cross-validation",
    "Parameters":   "-",
    "Std estimator": "\{$\hat{\sigma}_t$\}"
    },      {
    "Kernel": "$K_{t}$",
    "Method": "Cross-validation",
    "Parameters":   "df=\{3,4,5\}",
    "Std estimator": "\{$\hat{\sigma}_t$\}"
    },      {
    "Kernel": "$K_{t}$",
    "Method": "Adaptive",
    "Parameters":   "df=\{3,4,5\}",
    "Std estimator": "\{$\hat{\sigma}_t$\}"
    }]
df_kde_constants = pd.DataFrame(kde_constants)
df_kde_constants

,Kernel,Method,Parameters,Std estimator
0,$K_{gauss}$,Silverman,C(K) = 1.06,"\{$\hat{\sigma}_t$, $\hat{\sigma}_t^{IQR}$\}"
1,$K_{gauss}$,Adaptive,-,\{$\hat{\sigma}_t$\}
2,$K_{gauss}$,Cross-validation,-,\{$\hat{\sigma}_t$\}
3,$K_{gauss}$,SJ,-,\{$\hat{\sigma}_t$\}
4,$K_{gauss}$,ISJ,-,\{$\hat{\sigma}_t$\}
5,$K_{epan}$,Silverman,C(K) = 2.34,"\{$\hat{\sigma}_t$, $\hat{\sigma}_t^{IQR}$\}"
6,$K_{epan}$,Adaptive,-,\{$\hat{\sigma}_t$\}
7,$K_{epan}$,Cross-validation,-,\{$\hat{\sigma}_t$\}
8,$K_{t}$,Cross-validation,"df=\{3,4,5\}",\{$\hat{\sigma}_t$\}
9,$K_{t}$,Adaptive,"df=\{3,4,5\}",\{$\hat{\sigma}_t$\}

In [13]:
df_kde_constants.to_latex(
    buf     = '/'.join([out_path, "kde_constants_table.tex"]),
    caption = "KDE parameters.",
    label   = "tab:kde_constants",
    index   = False
    # convert_css=True,
    # column_format="c", #* len(cv_results_summary.columns)
    # hrules  = True
    )